domain.com:
  hostname: 52.198.32.9
  user: ubuntu
  port: 22
  identityFile: /Users/frankie/Documents/AmazonFile/default.pem
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  roles:
    - app
    - db
  deploy_path: /home/ubuntu/deploy/timer